query Categories {
  categories {
    id
    title
    subtitle
    image {
      url
    }
    articles {
      title
      subtitle
      content
      icon_class
      image {
        url
      }
    }
  }
}
